server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: proxy-service
  cloud:
    gateway:
      enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          order: 9000
          predicates:
            - Path=/client/**
        - id: agent-service
          uri: lb://agent-service
          order: 9000
          predicates:
            - Path=/agent/**
        - id: transfert-service
          uri: lb://transfert-service
          order: 9000
          predicates:
            - Path=/transfert/**
        - id: back-office-service
          uri: lb://back-office-service
          order: 9000
          predicates:
            - Path=/back-office/**
        - id: cmi-service
          uri: lb://cmi-service
          order: 9000
          predicates:
            - Path=/cmi/**
        - id: beneficiaire-service
          uri: lb://beneficiaire-service
          order: 9000
          predicates:
            - Path=/beneficiaire/**